---

- hosts: nginx
  become: yes
  roles:
     - role: openresty
  tags:
     - openresty

- hosts: mongodb
  become: yes
  roles:
     - role: mongodb
  tags:
     - mongodb

- hosts: jenkins-master
  become: yes
  roles:
     - jdk8
  tags:
     - jdk

- hosts: jenkins-master
  become: yes
  roles:
     - jenkins
     - jenkins-openresty-conf
  tags:
     - jenkins

- hosts: hubot
  become: yes
  roles:
     - ansible-role-nodejs
  tags:
     - nodejs

- hosts: hubot
  become: yes
  roles:
     - rocket-chat
  tags:
     - rocket-chat

- hosts: hubot
  become: yes
  roles:
     - ansible-hubot
  tags:
     - hubot


