---

- hosts: nginx
  become: yes
  roles:
     - role: openresty
  tags:
     - openresty

- hosts: mongodb
  become: yes
  roles:
     - role: mongodb
  tags:
     - mongodb

- hosts: jenkins-master
  become: yes
  roles:
     - jdk8
     - jenkins
    #  - openresty
     - jenkins-openresty-conf
  tags:
     - jenkins