---

nginx_conf_path: /usr/local/nginx/nginx/conf
nginx_stream_conf_path: "{{nginx_conf_path}}/streams"
nginx_servers_path: /usr/local/nginx/nginx/conf/servers
nginx_user: www
nginx_group: www

delegated_nginx_host: nginx
